### ISSUE TITLE
move GH Actions to new repository

### ISSUE THREAD

**Issue by memo33** [memo33/sc4pac#29]
With the emergence of [secondary channels](https://github.com/Zasco/sc4pac-channel), the GH actions should be moved to a central location. This requires some refactoring to make them more generic and configurable (e.g. `extra_channels`) to make them work smoothly for complementary channels that depend on information in other channels.

**Comment by Zasco** [comment]
This issue is closed by [memo33/sc4pac-actions](https://github.com/memo33/sc4pac-actions).

**Comment by memo33** [comment]
Solved by 13e35f297cae76e9539a4192d7eb1f1564d526d0.
