### ISSUE TITLE
UnicodeDecodeError when running sc4pac-yaml-schema.py on local folder

### ISSUE THREAD

**Issue by Zasco** [memo33/sc4pac#36]
When trying to run the channel linter on a local folder, I get the following error:

> Traceback (most recent call last):
  File "\sc4pac\channels\zasco\.gith
ub\sc4pac-yaml-schema.py", line 447, in <module>
    sys.exit(main())
             ~~~~^^
  File "\sc4pac\channels\zasco\.gith
ub\sc4pac-yaml-schema.py", line 334, in main
    text = f.read()
  File "\Python\Python313\Lib\encodings\cp
1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 546: char
acter maps to <undefined>

- _sc4pac_ version: [**0.4.6-SNAPSHOT**](https://github.com/memo33/sc4pac-tools/releases/tag/0.4.6-SNAPSHOT)
- OS: _Windows_ **8.1**
- Output of "_pyton_" command:
> Python 3.13.0 (tags/v3.13.0:60403a5, Oct  7 2024, 09:38:07) [MSC v.1941 64 bit (
AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
warning: can't use pyrepl: Windows 10 TH2 or later required

- Terminal: _Windows_ terminal

**Comment by memo33** [comment]
Thanks for the report. It looks like the default character encoding is platform dependent. Could you check if this change works for you?

```diff
diff --git a/.github/sc4pac-yaml-schema.py b/.github/sc4pac-yaml-schema.py
index 9100955..2bd106d 100644
--- a/.github/sc4pac-yaml-schema.py
+++ b/.github/sc4pac-yaml-schema.py
@@ -338,7 +338,7 @@ def main() -> int:
                 if not fname.endswith(".yaml"):
                     continue
                 p = os.path.join(root, fname)
-                with open(p) as f:
+                with open(p, encoding='utf-8') as f:
                     validated += 1
                     text = f.read()
                     try:
```

**Comment by Zasco** [comment]
> Thanks for the report. It looks like the default character encoding is platform dependent. Could you check if this change works for you?
> 
> ```diff
> diff --git a/.github/sc4pac-yaml-schema.py b/.github/sc4pac-yaml-schema.py
> index 9100955..2bd106d 100644
> --- a/.github/sc4pac-yaml-schema.py
> +++ b/.github/sc4pac-yaml-schema.py
> @@ -338,7 +338,7 @@ def main() -> int:
>                  if not fname.endswith(".yaml"):
>                      continue
>                  p = os.path.join(root, fname)
> -                with open(p) as f:
> +                with open(p, encoding='utf-8') as f:
>                      validated += 1
>                      text = f.read()
>                      try:
> ```

This fixed the problem. Thanks!

**Comment by memo33** [comment]
Thanks for confirming
