### ISSUE TITLE
Deploy action fails if any asset path has a space in it

### ISSUE THREAD

**Issue by Zasco** [memo33/sc4pac#58]
See https://github.com/Zasco/sc4pac-channel/actions/runs/12364758293 and https://github.com/Zasco/sc4pac-channel/actions/runs/12364820491

A check for this should be added to the linter.

**Comment by memo33** [comment]
This happens in combination with the new `--metadata-source-url` option. It is meant to convert the file path `src/hugues-aroux/ui-carbon-skin copy.yaml` to the following URL, which is referenced by the GUI:
```
https://github.com/Zasco/sc4pac-channel/blob/main/src/hugues-aroux/ui-carbon-skin%20copy.yaml
```
So, although I'd usually avoid spaces, a different proper fix would be to correctly percent-encode special characters when generating the URL.

At least for the main repo, I'd like to enforce "no spaces", so I'll probably do both.

**Comment by Zasco** [comment]
> So, although I'd usually avoid spaces [...]

I do too. Having folders hyphenated is welcome too. It didn't pop until now with that new feature.

> [...] a different proper fix would be to correctly percent-encode special characters when generating the URL.

That would handle that case, although it shouldn't be used.

> At least for the main repo, I'd like to enforce "no spaces", so I'll probably implement both patches.

Both cases handled; satisfaction reached. :D
